"""Blob measurements from Hesham's drawing: assets/avatar/trace.json -> BlobCharacter+Measurements.swift.

    python Tools/gen-blob-measurements.py          # writes the Swift file
    python Tools/gen-blob-measurements.py --check  # fails if the committed file is out of date (CI)

The numbers are measured from the traced drawing (683 drawing pixels = 1 m, the same units as
assets/avatar/build_avatar.py), never copied by hand: the head's silhouette (left and right averaged,
lightly smoothed, sampled every 24 pixel rows, with a small cap at the peak), where the eyes, brows,
cheeks and mouth sit on it, and the body's length and thickness.
"""

import json
import math
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TRACE = os.path.join(ROOT, "assets", "avatar", "trace.json")
OUT = os.path.join(ROOT, "Packages", "LoweyCore", "Sources", "LoweyCore", "Character", "BlobCharacter+Measurements.swift")

PX = 683.0
ROW_STEP = 24
SMOOTH = 4


def measure(trace):
    axis_x = trace["axis_x"]
    ground_y = trace["body"]["bbox"][1] + trace["body"]["bbox"][3] + 0.08 * PX

    def drawing_point(px, py):
        return (px - axis_x) / PX, (ground_y - py) / PX

    # Head: half widths, averaged over 2 × SMOOTH + 1 rows, sampled every ROW_STEP rows plus the lowest row.
    rows = trace["head_skin_rows"]
    halves = [(right - left) / 2 for _, left, right in rows]
    smooth = []
    for index in range(len(halves)):
        window = halves[max(0, index - SMOOTH) : index + SMOOTH + 1]
        smooth.append(sum(window) / len(window))
    bottom_row = rows[-1][0]
    picks = sorted(set(list(range(0, len(rows), ROW_STEP)) + [len(rows) - 1]))
    points = sorted(((smooth[i] / PX, (bottom_row - rows[i][0]) / PX) for i in picks), key=lambda p: p[1])
    profile = [(0.0, points[0][1] - 0.3 / PX)] + points
    # A small cap closes the peak, continuing the silhouette's slope (quadratic, three steps).
    (r1, z1), (r0, z0) = points[-2], points[-1]
    slope = (r1 - r0) / (z0 - z1)
    peak = z0 + 0.55 * r0 / slope
    control = (r0 - slope * (peak - z0), peak)
    for step in range(1, 4):
        t = step / 3
        r = (1 - t) ** 2 * r0 + 2 * (1 - t) * t * control[0]
        z = (1 - t) ** 2 * z0 + 2 * (1 - t) * t * control[1] + t * t * peak
        profile.append((r if step < 3 else 0.0, z))
    base = profile[0][1]
    profile = [(r, z - base) for r, z in profile]
    head_bottom = (ground_y - bottom_row) / PX - 0.3 / PX

    # Face: each mark's centre (left and right mirrored into one), above the head's bottom.
    face = trace["face"]

    def centroid(poly):
        return sum(p[0] for p in poly) / len(poly), sum(p[1] for p in poly) / len(poly)

    def mirrored(name):
        (lx, lz), (rx, rz) = (drawing_point(*centroid(face[f"{name}.{side}"][0])) for side in ("L", "R"))
        return (abs(lx) + abs(rx)) / 2, (lz + rz) / 2 - head_bottom

    def extent(poly, axis):
        values = [p[axis] for p in poly]
        return max(values) - min(values)

    eye_x, eye_y = mirrored("Eye")
    eye_rx = sum(extent(face[f"Eye.{side}"][0], 0) for side in ("L", "R")) / 4 / PX
    eye_ry = sum(extent(face[f"Eye.{side}"][0], 1) for side in ("L", "R")) / 4 / PX
    brow = mirrored("Brow")
    cheek = mirrored("Cheek")
    mouth_y = drawing_point(*centroid(face["Mouth"][0]))[1] - head_bottom

    # Body: the drop's length (tip to the far end) and thickness (its inflation).
    drawn = [drawing_point(x, y) for x, y, _ in trace["body_mesh"]["verts"]]
    tip = max(drawn, key=lambda p: p[1])
    far = max(drawn, key=lambda p: math.dist(p, tip))
    return {
        "profile": profile,
        "head_bottom": head_bottom,
        "eye": (eye_x, eye_y, eye_rx, eye_ry),
        "brow": brow,
        "cheek": cheek,
        "mouth_y": mouth_y,
        "body_length": math.dist(tip, far),
        "body_radius": trace["body_mesh"]["max_depth"] / PX,
        "ink": trace["ink_px"] / PX,
    }


def number(value):
    return f"{round(value, 4) + 0.0:.4f}"


def render(m):
    lines = []
    row = []
    for r, y in m["profile"]:
        row.append(f"({number(r)}, {number(y)})")
        if len(row) == 7:
            lines.append("        " + ", ".join(row))
            row = []
    if row:
        lines.append("        " + ", ".join(row))
    profile = ",\n".join(lines)
    eye = m["eye"]
    return f"""// Generated by Tools/gen-blob-measurements.py from assets/avatar/trace.json. Don't edit: change the drawing or the
// script and run it again (CI checks this file is up to date).

extension BlobCharacter {{
    /// Head silhouette (radius, height above the head's bottom), bottom to peak.
    static let headProfile: [(r: Double, y: Double)] = [
{profile}
    ]
    /// Height of the head's bottom above the ground in the drawing (before the hover).
    static let traceHeadBottom = {number(m["head_bottom"])}
    /// Face placement (x from the centre line, y above the head's bottom).
    static let eye = (x: {number(eye[0])}, y: {number(eye[1])}, rx: {number(eye[2])}, ry: {number(eye[3])})
    static let brow = (x: {number(m["brow"][0])}, y: {number(m["brow"][1])})
    static let cheek = (x: {number(m["cheek"][0])}, y: {number(m["cheek"][1])})
    static let mouthY = {number(m["mouth_y"])}
    /// The body: a drop this long and this thick.
    static let bodyLength = {number(m["body_length"])}
    static let bodyRadius = {number(m["body_radius"])}
    /// The drawing's line width.
    static let inkWidth = {number(m["ink"])}
}}
"""


def main():
    with open(TRACE, encoding="utf-8") as handle:
        text = render(measure(json.load(handle)))
    if "--check" in sys.argv:
        with open(OUT, encoding="utf-8") as handle:
            if handle.read() != text:
                print(f"{OUT} is out of date: run python Tools/gen-blob-measurements.py")
                sys.exit(1)
        print("Blob measurements are up to date.")
        return
    with open(OUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
