#!/usr/bin/env python3
"""docs/LAYOUT.md → AppUITests/LayoutWalk.swift: the rows the layout walk taps.

    python Tools/layout_walk.py           # write the Swift file
    python Tools/layout_walk.py --check   # CI: fail when the file doesn't match LAYOUT.md

A walk is a table row whose last cell is one code span: an optional precondition in brackets, then steps joined by
" › ". Rows whose last cell says something else (touch and hold a card, shown when…) are documented, not walked.
"""
from __future__ import annotations

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
LAYOUT = ROOT / "docs" / "LAYOUT.md"
OUTPUT = ROOT / "AppUITests" / "LayoutWalk.swift"
PRECONDITIONS = {"home", "cube", "blob", "timeline", "transport"}
WALK = re.compile(r"^`(?:\[(?P<pre>[a-z]+)\]\s*)?(?P<steps>[^`\[\]]+)`$")


def rows(text: str) -> list[tuple[str, str, str, list[str]]]:
    found = []
    section = ""
    last_control = ""
    for line in text.splitlines():
        if line.startswith("#"):
            section = line.lstrip("#").strip()
            continue
        if not line.startswith("|") or line.startswith("|---"):
            continue
        cells = [cell.strip() for cell in line.strip().strip("|").split("|")]
        if len(cells) < 2:
            continue
        control, walk = cells[0], cells[-1]
        match = WALK.match(walk)
        if not match:
            continue
        pre = match.group("pre") or ""
        if pre and pre not in PRECONDITIONS:
            raise SystemExit(f"LAYOUT.md: unknown precondition [{pre}] in {line!r}")
        steps = [step.strip() for step in match.group("steps").split("›")]
        if any(not step for step in steps):
            raise SystemExit(f"LAYOUT.md: an empty step in {line!r}")
        control = control or last_control
        last_control = control
        found.append((section, control, pre, steps))
    return found


def swift(found: list[tuple[str, str, str, list[str]]]) -> str:
    def literal(value: str) -> str:
        return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'

    lines = [
        "// Generated by Tools/layout_walk.py from docs/LAYOUT.md. Don't edit: change LAYOUT.md and run the tool.",
        "",
        "/// Every walkable row of docs/LAYOUT.md: where a control lives and the taps that reach it.",
        "enum LayoutWalk {",
        "    struct Row {",
        "        let home: String",
        "        let precondition: String",
        "        let control: String",
        "        let steps: [String]",
        "    }",
        "",
        "    static let rows = layoutWalkRows",
        "}",
        "",
        "/// The rows, outside the enum so its body stays short however many rows LAYOUT.md holds.",
        "private let layoutWalkRows: [LayoutWalk.Row] = [",
    ]
    for index, (section, control, pre, steps) in enumerate(found):
        lines += [
            f"    LayoutWalk.Row(home: {literal(section)}, precondition: {literal(pre)},",
            f"                   control: {literal(control)},",
            f"                   steps: [{', '.join(literal(step) for step in steps)}])" + ("," if index < len(found) - 1 else ""),
        ]
    lines += ["]", ""]
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    found = rows(LAYOUT.read_text(encoding="utf-8"))
    text = swift(found)
    if "--check" in argv:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != text:
            print("AppUITests/LayoutWalk.swift doesn't match docs/LAYOUT.md: run python Tools/layout_walk.py", file=sys.stderr)
            return 1
        print(f"The layout walk matches LAYOUT.md ({len(found)} rows).")
        return 0
    OUTPUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"Wrote {OUTPUT.relative_to(ROOT)} ({len(found)} rows).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
